from __future__ import annotations

from datetime import UTC, datetime
from html import escape
from pathlib import Path
from typing import Any

from yacht.reports.provenance_format import (
    provenance_harness_label,
    provenance_mixed,
    provenance_model_label,
    provenance_tools_label,
)

_STYLE = """
:root {
  --bg: #ffffff; --fg: #1a1f2e; --muted: #5b6472; --line: #e3e7ee;
  --card: #f6f8fb; --good: #157347; --good-bg: #e6f4ec;
  --bad: #b02a37; --bad-bg: #f8e7e9; --tied: #5b6472; --tied-bg: #eef0f4;
  --warn: #8a6d1a; --warn-bg: #fbf3d9; --bar-a: #5b7fd4; --bar-b: #d48a5b;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #14171e; --fg: #e6e9f0; --muted: #98a0ae; --line: #2a2f3a;
    --card: #1c2029; --good: #4ade80; --good-bg: #12291c;
    --bad: #f87171; --bad-bg: #2d1a1d; --tied: #98a0ae; --tied-bg: #22262f;
    --warn: #facc15; --warn-bg: #2b2413; --bar-a: #7c9aea; --bar-b: #e0a077;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0 auto; padding: 2rem 1.25rem 4rem; max-width: 64rem;
  background: var(--bg); color: var(--fg);
  font: 15px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif;
}
h1 { font-size: 1.45rem; margin: 0 0 0.25rem; }
h2 { font-size: 1.05rem; margin: 2.2rem 0 0.7rem; }
code, .mono { font-family: ui-monospace, "SF Mono", Menlo, monospace; font-size: 0.86em; }
.sub { color: var(--muted); margin: 0 0 1.4rem; }
.verdict { border-radius: 10px; padding: 1rem 1.2rem; margin: 1rem 0; border: 1px solid var(--line); }
.verdict.improved { background: var(--good-bg); border-color: var(--good); }
.verdict.regressed { background: var(--bad-bg); border-color: var(--bad); }
.verdict.tied { background: var(--tied-bg); }
.verdict .headline { font-size: 1.1rem; font-weight: 650; }
.verdict.improved .headline { color: var(--good); }
.verdict.regressed .headline { color: var(--bad); }
.verdict .detail { color: var(--muted); margin-top: 0.25rem; }
.badge {
  display: inline-block; border-radius: 999px; padding: 0.1rem 0.6rem;
  font-size: 0.78rem; font-weight: 600; background: var(--warn-bg); color: var(--warn);
  vertical-align: middle; margin-left: 0.5rem;
}
.badge.good { background: var(--good-bg); color: var(--good); }
table { border-collapse: collapse; width: 100%; margin: 0.5rem 0 1rem; }
th, td { text-align: left; padding: 0.42rem 0.7rem; border-bottom: 1px solid var(--line); }
th { color: var(--muted); font-weight: 600; font-size: 0.82rem; text-transform: uppercase; letter-spacing: 0.03em; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
.ok { color: var(--good); font-weight: 600; }
.fail { color: var(--bad); font-weight: 600; }
.muted { color: var(--muted); }
.card { background: var(--card); border: 1px solid var(--line); border-radius: 10px; padding: 0.9rem 1.1rem; margin: 0.6rem 0; }
svg text { fill: var(--fg); font: 12px system-ui, sans-serif; }
svg .axis { fill: var(--muted); }
footer { margin-top: 3rem; color: var(--muted); font-size: 0.82rem; }
"""


def render_benchmark_html(
    *,
    scorecard: dict[str, Any],
    task_attempt_scorecard: dict[str, Any] | None,
    logbook_dir: Path,
) -> str:
    body: list[str] = []
    body.append(f"<h1>{_e(scorecard['regatta'])}</h1>")
    body.append(
        '<p class="sub">'
        f"Course <code>{_e(scorecard['course'])}</code> &middot; "
        f"status <code>{_e(scorecard['status'])}</code> &middot; "
        f"logbook <code>{_e(str(logbook_dir))}</code></p>"
    )
    attempts_by_comparison = _attempt_comparisons(task_attempt_scorecard)
    for comparison in scorecard["comparisons"]:
        body.extend(
            _comparison_sections(
                comparison,
                attempts_by_comparison.get(str(comparison["name"])),
            )
        )
    body.extend(_next_steps_section(scorecard.get("next_steps")))
    generated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    body.append(
        f"<footer>Generated by YACHT on {_e(generated)} from "
        f"<code>benchmark-scorecard.json</code> in <code>{_e(str(logbook_dir))}"
        "</code>. All numbers come from logbook artifacts.</footer>"
    )
    return _page(f"YACHT: {scorecard['regatta']}", body)


def render_benchmark_aggregate_html(aggregate: dict[str, Any]) -> str:
    body: list[str] = []
    body.append(f"<h1>{_e(str(aggregate['regatta']))}</h1>")
    run_count = int(aggregate["run_count"])
    body.append(
        '<p class="sub">'
        f"Course <code>{_e(str(aggregate['course']))}</code> &middot; "
        f"{run_count} repeated run{'s' if run_count != 1 else ''}</p>"
    )
    for comparison in aggregate["comparisons"]:
        body.extend(_aggregate_comparison_sections(comparison, run_count))
    logbooks = "".join(
        f"<li><code>{_e(str(logbook))}</code></li>"
        for logbook in aggregate.get("logbooks", [])
    )
    if logbooks:
        body.append(f"<h2>Run logbooks</h2><ul>{logbooks}</ul>")
    generated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    body.append(
        f"<footer>Generated by YACHT on {_e(generated)} from "
        f"{run_count} benchmark logbooks. All numbers come from logbook "
        "artifacts.</footer>"
    )
    return _page(f"YACHT: {aggregate['regatta']} ({run_count} runs)", body)


def _aggregate_comparison_sections(
    comparison: dict[str, Any],
    run_count: int,
) -> list[str]:
    sections: list[str] = []
    sections.append(f"<h2>Comparison: {_e(str(comparison['name']))}</h2>")
    sections.append(_aggregate_verdict_card(comparison, run_count))
    sections.append(_aggregate_vessel_table(comparison))
    provenance_table = _aggregate_provenance_table(comparison)
    if provenance_table:
        sections.append("<h2>Provenance</h2>")
        sections.append(provenance_table)
    runs_table = _aggregate_runs_table(comparison)
    if runs_table:
        sections.append("<h2>Per-run deltas</h2>")
        sections.append(runs_table)
    return sections


def _aggregate_verdict_card(comparison: dict[str, Any], run_count: int) -> str:
    delta = comparison["delta"]
    stats = comparison.get("delta_statistics", {})
    resolved_delta = int(delta["resolved_instances_delta"])
    baseline = str(delta["baseline_vessel"])
    challenger = str(delta["challenger_vessel"])
    if resolved_delta > 0:
        kind = "improved"
        headline = f"{challenger} resolved {resolved_delta} more across all runs"
    elif resolved_delta < 0:
        kind = "regressed"
        headline = f"{challenger} resolved {-resolved_delta} fewer across all runs"
    else:
        kind = "tied"
        headline = f"{challenger} tied with {baseline} across all runs"
    badge = _variance_badge(stats.get("resolved_instances_delta"), run_count)
    badge += _mixed_provenance_badge(comparison)
    detail = (
        f"Baseline <code>{_e(baseline)}</code> vs challenger "
        f"<code>{_e(challenger)}</code> &middot; total resolution rate delta "
        f"{float(delta['resolution_rate_delta']):+.3f} &middot; "
        f"{run_count} run{'s' if run_count != 1 else ''}"
    )
    return (
        f'<div class="verdict {kind}"><span class="headline">{_e(headline)}'
        f"</span>{badge}"
        f'<div class="detail">{detail}</div></div>'
    )


def _mixed_provenance_badge(comparison: dict[str, Any]) -> str:
    mixed: set[str] = set()
    for vessel in comparison.get("vessels", []):
        provenance = vessel.get("provenance")
        if isinstance(provenance, dict):
            mixed.update(provenance_mixed(provenance))
    if not mixed:
        return ""
    return (
        '<span class="badge">mixed provenance across runs: '
        f"{_e(', '.join(sorted(mixed)))}</span>"
    )


def _aggregate_provenance_table(comparison: dict[str, Any]) -> str:
    rows = []
    for vessel in comparison.get("vessels", []):
        provenance = vessel.get("provenance")
        if not isinstance(provenance, dict):
            continue
        mixed = provenance_mixed(provenance)
        mixed_cell = (
            f'<td class="fail">{_e(", ".join(mixed))}</td>'
            if mixed
            else '<td class="muted">none</td>'
        )
        rows.append(
            f"<tr><td>{_e(str(vessel['name']))}</td>"
            f"<td><code>{_e(provenance_harness_label(provenance))}</code></td>"
            f"<td><code>{_e(provenance_model_label(provenance))}</code></td>"
            f"<td><code>{_e(provenance_tools_label(provenance))}</code></td>"
            f"{mixed_cell}</tr>"
        )
    if not rows:
        return ""
    return (
        "<table><tr><th>Vessel</th><th>Harness</th><th>Model</th>"
        "<th>Tools</th><th>Mixed dimensions</th></tr>" + "".join(rows) + "</table>"
    )


def _variance_badge(delta_stats: Any, run_count: int) -> str:
    if not isinstance(delta_stats, dict) or run_count < 2:
        return '<span class="badge">single run: no variance estimate</span>'
    mean = float(delta_stats.get("mean") or 0.0)
    stdev = float(delta_stats.get("stdev") or 0.0)
    if stdev == 0.0:
        return f'<span class="badge good">consistent across {run_count} runs</span>'
    if abs(mean) <= stdev:
        return (
            '<span class="badge">within run-to-run variance '
            f"(mean {mean:+.2f} &plusmn; {stdev:.2f})</span>"
        )
    return (
        '<span class="badge good">exceeds run variance '
        f"(mean {mean:+.2f} &plusmn; {stdev:.2f})</span>"
    )


def _aggregate_vessel_table(comparison: dict[str, Any]) -> str:
    rows = [
        '<table><tr><th>Vessel</th><th class="num">Measured runs</th>'
        '<th class="num">Resolved</th><th class="num">Rate mean &plusmn; stdev'
        '</th><th class="num">Tokens mean &plusmn; stdev</th>'
        '<th class="num">Cost mean &plusmn; stdev</th>'
        '<th class="num">Duration mean &plusmn; stdev</th></tr>'
    ]
    for vessel in comparison["vessels"]:
        stats = vessel.get("statistics", {})
        rows.append(
            f"<tr><td><code>{_e(str(vessel['name']))}</code></td>"
            f'<td class="num">{vessel["measured_runs"]}/{vessel["runs"]}</td>'
            f'<td class="num">{vessel["resolved_instances"]}'
            f"/{vessel['submitted_instances']}</td>"
            f'<td class="num">{_mean_stdev(stats.get("resolution_rate"), "{:.3f}")}'
            "</td>"
            f'<td class="num">{_mean_stdev(stats.get("tokens"), "{:,.0f}")}</td>'
            f'<td class="num">{_mean_stdev(stats.get("cost"), "{:.4f}")}</td>'
            f'<td class="num">{_mean_stdev(stats.get("duration_seconds"), "{:.1f}")}'
            "</td></tr>"
        )
    rows.append("</table>")
    return "".join(rows)


def _aggregate_runs_table(comparison: dict[str, Any]) -> str:
    runs = comparison.get("runs", [])
    if not runs:
        return ""
    rows = [
        '<table><tr><th class="num">Run</th><th>Logbook</th>'
        '<th class="num">Resolved delta</th>'
        '<th class="num">Rate delta</th><th class="num">Tokens delta</th>'
        "</tr>"
    ]
    for run in runs:
        delta = run.get("delta", {})
        rows.append(
            f'<tr><td class="num">{run.get("index", "-")}</td>'
            f"<td><code>{_e(_short(str(run.get('logbook', '-')), 48))}</code></td>"
            f'<td class="num">{int(delta.get("resolved_instances_delta") or 0):+d}'
            "</td>"
            f'<td class="num">{float(delta.get("resolution_rate_delta") or 0):+.3f}'
            "</td>"
            f'<td class="num">{int(delta.get("tokens_delta") or 0):+,d}</td></tr>'
        )
    rows.append("</table>")
    return "".join(rows)


def _mean_stdev(stats: Any, pattern: str) -> str:
    if not isinstance(stats, dict):
        return "-"
    mean = pattern.format(float(stats.get("mean") or 0.0))
    stdev = pattern.format(float(stats.get("stdev") or 0.0))
    return f"{mean} &plusmn; {stdev}"


def render_smoke_html(
    *,
    smoke_status: dict[str, Any],
    logbook_dir: Path,
) -> str:
    body: list[str] = []
    body.append("<h1>Smoke run</h1>")
    status = str(smoke_status.get("status"))
    kind = "improved" if status == "ready" else "regressed"
    body.append(
        f'<div class="verdict {kind}"><span class="headline">'
        f"Smoke status: {_e(status)}</span>"
        f'<div class="detail">Logbook <code>{_e(str(logbook_dir))}</code></div></div>'
    )
    body.append("<h2>Artifacts</h2><table>")
    body.append("<tr><th>Artifact</th><th>Present</th><th>Path</th></tr>")
    for artifact in smoke_status.get("artifacts", []):
        marker = (
            '<span class="ok">present</span>'
            if artifact.get("present")
            else '<span class="fail">missing</span>'
        )
        body.append(
            f"<tr><td>{_e(str(artifact.get('name')))}</td><td>{marker}</td>"
            f"<td><code>{_e(str(artifact.get('path')))}</code></td></tr>"
        )
    body.append("</table>")
    body.append(
        f'<p class="muted">Next: <code>{_e(str(smoke_status.get("next_step")))}'
        "</code></p>"
    )
    return _page("YACHT: smoke run", body)


def _comparison_sections(
    comparison: dict[str, Any],
    attempt_comparison: dict[str, Any] | None,
) -> list[str]:
    sections: list[str] = []
    sections.append(f"<h2>Comparison: {_e(str(comparison['name']))}</h2>")
    sections.append(_verdict_card(comparison))
    sections.append(_vessel_table(comparison, attempt_comparison))
    if attempt_comparison is not None:
        usage_chart = _usage_chart(attempt_comparison)
        if usage_chart:
            sections.append("<h2>Usage</h2>")
            sections.append(usage_chart)
        tool_table = _tool_call_table(attempt_comparison)
        if tool_table:
            sections.append("<h2>Tool calls</h2>")
            sections.append(
                '<p class="muted">Evidence that a challenger tool was actually '
                "used, not just installed.</p>"
            )
            sections.append(tool_table)
    task_table = _task_outcomes(comparison)
    if task_table:
        sections.append("<h2>Task outcomes</h2>")
        sections.append(task_table)
    return sections


def _verdict_card(comparison: dict[str, Any]) -> str:
    delta = comparison.get("delta")
    if not isinstance(delta, dict):
        return (
            '<div class="verdict tied"><span class="headline">No comparison '
            "delta recorded</span></div>"
        )
    resolved_delta = int(delta["resolved_instances_delta"])
    rate_delta = float(delta["resolution_rate_delta"])
    baseline = str(delta["baseline_vessel"])
    challenger = str(delta["challenger_vessel"])
    if resolved_delta > 0:
        kind, headline = "improved", f"{challenger} resolved {resolved_delta} more"
    elif resolved_delta < 0:
        kind, headline = "regressed", f"{challenger} resolved {-resolved_delta} fewer"
    else:
        kind, headline = "tied", f"{challenger} tied with {baseline} on resolution"
    submitted = _max_submitted(comparison)
    badge = ""
    if submitted < 5:
        badge = (
            '<span class="badge">small sample: '
            f"{submitted} task{'s' if submitted != 1 else ''}, single run"
            "</span>"
        )
    detail = (
        f"Baseline <code>{_e(baseline)}</code> vs challenger "
        f"<code>{_e(challenger)}</code> &middot; resolution rate delta "
        f"{rate_delta:+.3f}"
    )
    return (
        f'<div class="verdict {kind}"><span class="headline">{_e(headline)}'
        f"</span>{badge}"
        f'<div class="detail">{detail}</div></div>'
    )


def _vessel_table(
    comparison: dict[str, Any],
    attempt_comparison: dict[str, Any] | None,
) -> str:
    usage = _attempt_vessels(attempt_comparison)
    rows = [
        '<table><tr><th>Vessel</th><th>Preflight</th><th class="num">Resolved'
        '</th><th class="num">Rate</th><th class="num">Tokens</th>'
        '<th class="num">Cost</th><th class="num">Duration</th></tr>'
    ]
    for vessel in comparison["vessels"]:
        name = str(vessel["name"])
        preflight = str(vessel.get("preflight_status", "unknown"))
        preflight_class = "ok" if preflight == "passed" else "fail"
        vessel_usage = usage.get(name, {})
        rows.append(
            f"<tr><td><code>{_e(name)}</code></td>"
            f'<td><span class="{preflight_class}">{_e(preflight)}</span></td>'
            f'<td class="num">{vessel.get("resolved_instances", "-")}'
            f"/{vessel.get('submitted_instances', '-')}</td>"
            f'<td class="num">{_rate(vessel.get("resolution_rate"))}</td>'
            f'<td class="num">{_num(vessel_usage.get("total_tokens"))}</td>'
            f'<td class="num">{_cost(vessel_usage.get("total_cost"))}</td>'
            f'<td class="num">{_seconds(vessel_usage.get("total_duration_seconds"))}'
            "</td></tr>"
        )
    rows.append("</table>")
    return "".join(rows)


def _usage_chart(attempt_comparison: dict[str, Any]) -> str:
    vessels = attempt_comparison.get("vessels", [])
    if not vessels:
        return ""
    metrics = (
        ("total_tokens", "tokens", _num),
        ("total_cost", "cost ($)", _cost),
        ("total_duration_seconds", "duration (s)", _seconds),
        ("tool_call_count", "tool calls", _num),
    )
    label_width, bar_width, row_height = 190, 360, 22
    groups: list[str] = []
    y = 0
    for key, label, fmt in metrics:
        values = [(str(v["name"]), float(v.get(key) or 0)) for v in vessels]
        top = max((value for _, value in values), default=0.0)
        groups.append(f'<text x="0" y="{y + 15}" class="axis">{_e(label)}</text>')
        y += row_height
        for index, (name, value) in enumerate(values):
            width = 0 if top == 0 else max(2, round(bar_width * value / top))
            color = "var(--bar-a)" if index == 0 else "var(--bar-b)"
            groups.append(
                f'<rect x="{label_width}" y="{y + 4}" width="{width}" '
                f'height="{row_height - 9}" rx="3" fill="{color}"></rect>'
                f'<text x="0" y="{y + 15}">{_e(_short(name))}</text>'
                f'<text x="{label_width + width + 8}" y="{y + 15}">'
                f"{_e(fmt(value))}</text>"
            )
            y += row_height
        y += 10
    return (
        f'<svg viewBox="0 0 640 {y}" width="100%" height="{y}" '
        f'role="img" aria-label="usage comparison">{"".join(groups)}</svg>'
    )


def _tool_call_table(attempt_comparison: dict[str, Any]) -> str:
    vessels = attempt_comparison.get("vessels", [])
    tools = sorted(
        {tool for vessel in vessels for tool in (vessel.get("tool_call_counts") or {})}
    )
    if not tools:
        return ""
    header = "".join(f'<th class="num">{_e(tool)}</th>' for tool in tools)
    rows = [f"<table><tr><th>Vessel</th>{header}</tr>"]
    for vessel in vessels:
        counts = vessel.get("tool_call_counts") or {}
        cells = "".join(f'<td class="num">{counts.get(tool, 0)}</td>' for tool in tools)
        rows.append(f"<tr><td><code>{_e(str(vessel['name']))}</code></td>{cells}</tr>")
    rows.append("</table>")
    return "".join(rows)


def _task_outcomes(comparison: dict[str, Any]) -> str:
    vessels = comparison["vessels"]
    task_ids = sorted(
        {
            str(task_id)
            for vessel in vessels
            for task_id in [
                *(vessel.get("resolved_ids") or []),
                *(vessel.get("unresolved_ids") or []),
            ]
        }
    )
    if not task_ids:
        return ""
    header = "".join(f"<th>{_e(str(vessel['name']))}</th>" for vessel in vessels)
    rows = [f"<table><tr><th>Task</th>{header}</tr>"]
    for task_id in task_ids:
        cells = []
        for vessel in vessels:
            if task_id in (vessel.get("resolved_ids") or []):
                cells.append('<td><span class="ok">resolved</span></td>')
            elif task_id in (vessel.get("unresolved_ids") or []):
                cells.append('<td><span class="fail">unresolved</span></td>')
            else:
                cells.append('<td><span class="muted">-</span></td>')
        rows.append(f"<tr><td><code>{_e(task_id)}</code></td>{''.join(cells)}</tr>")
    rows.append("</table>")
    return "".join(rows)


def _next_steps_section(next_steps: Any) -> list[str]:
    if not isinstance(next_steps, list) or not next_steps:
        return []
    items = []
    for step in next_steps:
        if not isinstance(step, dict):
            continue
        command = step.get("command_preview") or " ".join(
            str(part) for part in step.get("command", [])
        )
        items.append(
            f"<li>{_e(str(step.get('label', 'Next step')))}: "
            f"<code>{_e(command)}</code></li>"
        )
    if not items:
        return []
    return ["<h2>Next steps</h2>", f"<ul>{''.join(items)}</ul>"]


def _attempt_comparisons(
    task_attempt_scorecard: dict[str, Any] | None,
) -> dict[str, dict[str, Any]]:
    if not isinstance(task_attempt_scorecard, dict):
        return {}
    return {
        str(comparison["name"]): comparison
        for comparison in task_attempt_scorecard.get("comparisons", [])
        if isinstance(comparison, dict)
    }


def _attempt_vessels(
    attempt_comparison: dict[str, Any] | None,
) -> dict[str, dict[str, Any]]:
    if not isinstance(attempt_comparison, dict):
        return {}
    return {
        str(vessel["name"]): vessel
        for vessel in attempt_comparison.get("vessels", [])
        if isinstance(vessel, dict)
    }


def _max_submitted(comparison: dict[str, Any]) -> int:
    return max(
        (
            int(vessel.get("submitted_instances") or 0)
            for vessel in comparison["vessels"]
        ),
        default=0,
    )


def render_page(title: str, body: list[str]) -> str:
    """Public wrapper so other surfaces (yacht serve) share the page chrome."""
    return _page(title, body)


def _page(title: str, body: list[str]) -> str:
    return (
        '<!doctype html><html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f"<title>{_e(title)}</title><style>{_STYLE}</style></head><body>"
        f"{''.join(body)}</body></html>\n"
    )


def _e(value: str) -> str:
    return escape(str(value), quote=True)


def _rate(value: Any) -> str:
    if value is None:
        return "-"
    return f"{float(value):.3f}"


def _num(value: Any) -> str:
    if value is None:
        return "-"
    return f"{int(value):,}"


def _cost(value: Any) -> str:
    if value is None:
        return "-"
    return f"{float(value):.4f}"


def _seconds(value: Any) -> str:
    if value is None:
        return "-"
    return f"{float(value):.1f}s"


def _short(name: str, limit: int = 24) -> str:
    return name if len(name) <= limit else name[: limit - 1] + "…"
